@baseUrl = http://localhost:3000/v1

### Get all orders
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a new order
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "userId": 6,
  "description": "order from user 6",
  "paymentType": "CASH",
  "total": 1000
}

### Update order payment status
PATCH {{baseUrl}}/orders/{{testOrderId}}
Content-Type: application/json

{
  "paymentStatus": "PAID"
}

### Create a checkout session
POST {{baseUrl}}/orders/checkout-sessions
Content-Type: application/json

{
  "userId": 7,
  "description": "order from user 7",
  "paymentType": "CASH",
  "total": 90000,
  "lineItems": [
    {
      "stripePriceId": "price_1S1F0hKA1oovtT3Z0sIQpKiz",
      "quantity": 2
    }
  ]
}
