/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FRONTEND_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}